### PR TITLE
Use latest npm packages.

### PR DESCRIPTION
**Pull request by cristianoc**

### CODE REVIEW

**Review by mununki — APPROVED** [review]

**Comment by cristianoc** [comment]
This does not compile:
```res
    <FancyInput className="fancy" ref=input>
```

**Comment by mununki** [comment]
> This does not compile:
> 
> ```rescript
>     <FancyInput className="fancy" ref=input>
> ```

Can you pull the latest commit in main branch which I just committed?

**Comment by cristianoc** [comment]
@mattdamon108 time for another round of feedback from the forum?

**Comment by mununki** [comment]
> @mattdamon108 time for another round of feedback from the forum?

Perfect time I guess. I’ll post it.

**Pull request merged**
